[workspace]
resolver = "2"
members = [ 
    "ctor", 
    "dtor", 
    "macro-magic",
    "linktime",
    "linktime-proc-macro",
    "link-section",
    "tests"
]
default-members = [
    "ctor",
    "dtor",
    "macro-magic",
    "link-section",
    "tests"
]
exclude = []

[workspace.package]
authors = ["Matt Mastracci <matthew@mastracci.com>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/rust-ctor"

[workspace.dependencies]
ctor = { path = "ctor", default-features = false }
dtor = { path = "dtor", version = "0.11.0", default-features = false }
link-section = { path = "link-section", version = "0.11.0", default-features = false }

linktime-proc-macro = { path = "linktime-proc-macro", version = "0.1.0" }
