[package]
name = "scattered-collect-proc-macro"
version = "0.1.0"
edition = "2021"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
description = "proc-macro support for the scattered-collect crate"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/scattered-collect"

[lib]
proc-macro = true
