[package]
name = "scattered-collect-proc-macro"
version = "0.1.0"
edition = "2021"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
description = "proc-macro support for scattered-collect (link-time collections)"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/scattered-collect"
categories = ["development-tools::procedural-macro-helpers", "development-tools::build-utils"]

[lib]
proc-macro = true
