[package]
name = "tests-edition-2021"
version = "0.1.0"
edition = "2021"
publish = false

[features]

[dependencies]
# When we bump the MSRV, can probably re-add priority feature.
ctor = { path = "../../../ctor", default-features = false, features = ["proc_macro", "std"] }
libc-print = "0.3"

[workspace]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(linktime_no_fail_on_missing_unsafe)',
    'cfg(linktime_used_linker)'
] }
