[package]
name = "tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ctor = { path = "../../../ctor" }
link-section = { path = "../../../link-section" }
libc-print = "0.5"

[profile.dev]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[workspace]
