use core::sync::atomic::{AtomicBool, Ordering};

extern "C" {
    // Generated by wasm-ld; runs every `.init_array` constructor, which is how
    // the `link-section` items are registered and the section is flattened.
    fn __wasm_call_ctors();
}

static STARTED: AtomicBool = AtomicBool::new(false);

/// Run constructors exactly once. `wasm32-unknown-unknown` does not call these
/// automatically, so the host invokes this before reading the section.
#[no_mangle]
pub extern "C" fn init() {
    if !STARTED.swap(true, Ordering::SeqCst) {
        // Anchor the `items` crate so its constructors are linked in.
        items::touch();
        unsafe {
            __wasm_call_ctors();
        }
    }
}

/// Number of items registered into the section.
#[no_mangle]
pub extern "C" fn items_len() -> usize {
    section_def::ITEMS.len()
}

/// Sum of all item values, to confirm each item's value survived.
#[no_mangle]
pub extern "C" fn items_sum() -> u32 {
    section_def::ITEMS.as_slice().iter().map(|item| item.0).sum()
}
