[package]
name = "tests-edition-2024"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.85"

[features]

[dependencies]
ctor = { path = "../../../ctor" }
libc-print = "0.5"

[workspace]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(linktime_no_fail_on_missing_unsafe)',
    'cfg(linktime_used_linker)'
] }
